pub const BITCOIN_ADDRESS_VERSION_PREFIX: u8 = 0x00;
pub const BITCOIN_P2SH_VERSION_PREFIX: u8 = 0x05;
pub const BITCOIN_TESTNET_ADDRESS_VERSION_PREFIX: u8 = 0x6F;
pub const BITCOIN_PRIVATE_KEY_WIF_VERSION_PREFIX: u8 = 0x80;
pub const BITCOIN_TESTNET_PRIVATE_KEY_WIF_VERSION_PREFIX: u8 = 0xef;
pub const BITCOIN_WIF_COMPRESSED_SUFFIX: u8 = 0x01;
